version: "3"
services:
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  test:
    image: "exercise-5"
    volumes:
      - .:/app
    command: python3 -m pytest

  run:
    image: "exercise-5"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: python3 main.py

volumes:
  postgres-db-volume:
  pgadmin-data:
